FROM osrf/ros:humble-desktop

# Define user argument with default value
ARG USER_NAME=myuser1
ARG USER_ID=1000
ARG GROUP_ID=1000

# Install necessary packages before adding user
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git nano gedit python3 python3-pip sudo wget lsb-release gnupg curl

# Setting up Gazebo repository and ROS 2 repository
RUN wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null && \
    apt-get update -y

RUN sudo sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros2-latest.list' && \
    curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add - && \
    sudo apt-get update -y && \
    sudo apt-get install -y python3-vcstool python3-colcon-common-extensions

# Create a non-root user
RUN useradd --create-home --shell /bin/bash ${USER_NAME} && \
    echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    mkdir -p /home/${USER_NAME}/workspace && \
    mkdir -p /home/${USER_NAME}/gz && \
    chown -R ${USER_NAME}:${USER_NAME} /home/${USER_NAME}

RUN echo "source /opt/ros/humble/setup.bash" >> /home/${USER_NAME}/.bashrc

# Switch to the new user
USER ${USER_NAME}
WORKDIR /home/${USER_NAME}/gz

ENV PATH="/home/${USER_NAME}/.local/bin:${PATH}"

RUN mkdir -p src && \
    cd src && \
    wget https://raw.githubusercontent.com/gazebo-tooling/gazebodistro/master/collection-garden.yaml && \
    vcs import < collection-garden.yaml && \
    sudo apt-get update && \
    sudo apt -y install \
    $(sort -u $(find . -iname 'packages-'`lsb_release -cs`'.apt' -o -iname 'packages.apt' | grep -v '/\.git/') | sed '/gz\|sdf/d' | tr '\n' ' ')

RUN cd /home/${USER_NAME}/gz/src && \
    rm -rdf gz-sim || true && \
    git clone https://github.com/UoA-CARES/gz-sim.git && \
    cd /home/${USER_NAME}/gz && \
    colcon build --merge-install

RUN echo "source /home/${USER_NAME}/gz/install/setup.bash" >> /home/${USER_NAME}/.bashrc

WORKDIR /home/${USER_NAME}/workspace

# Install the CARES Reinforcement Learning package and its dependencies
RUN python3 -m pip install --user --upgrade pip setuptools wheel

RUN git clone https://github.com/UoA-CARES/cares_reinforcement_learning.git /home/${USER_NAME}/workspace/cares_reinforcement_learning && \
    cd /home/${USER_NAME}/workspace/cares_reinforcement_learning && \
    python3 -m pip install --user -e ".[gym]"

RUN mkdir -p /home/${USER_NAME}/ros2_ws/src && \
    cd /home/${USER_NAME}/ros2_ws && \ 
    rosdep update -y

# Downgrade setuptools to avoid compatibility issues with some ROS 2 packages
RUN python3 -m pip install --user "setuptools<69"

# Set working directory
WORKDIR /home/${USER_NAME}

ENTRYPOINT ["/bin/bash", "-i"]

