sim:
  ros__parameters:
    algorithm: 'ftg'
    observation_mode: 'lidar_only'
    environment: 'CarGoal'
    track: 'aruco_test'
    start_stage: 'track' # init, plan, track
    number_eval_episodes: 100
    path_file_path: 'newpath.txt'
